#!/usr/bin/env python3
"""Analyze all RB12 fonts in fonts/ — metrics for Apple2026 tuning."""

from __future__ import annotations

import argparse
from pathlib import Path

from rb12_metrics import RBFont, digit_width_stats, font_info, ink_ratio_sample

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "fonts"
REPORT = FONTS_DIR / "APPLE2026_FONT_ANALYSIS.md"

SAMPLE_MENU = "Library Playlists Artists Albums"
SAMPLE_BODY = "Now Playing — Track 07"


def analyze_all(fonts_dir: Path) -> str:
    paths = sorted(fonts_dir.glob("*.fnt"))
    lines: list[str] = []
    lines.append("# Apple2026 RB12 font analysis\n")
    lines.append("Auto-generated by `tools/analyze_rb12_fonts.py`.\n")
    lines.append("| File | h | ascent | maxw | digit span | ink(menu) | ink(body) |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")

    for p in paths:
        try:
            f = RBFont(p)
            info = font_info(p)
            dmin, dmax, _ = digit_width_stats(f)
            im = ink_ratio_sample(f, SAMPLE_MENU)
            ib = ink_ratio_sample(f, SAMPLE_BODY)
            lines.append(
                f"| `{p.name}` | {info.height} | {info.ascent} | {info.maxwidth} | "
                f"{dmin} to {dmax} | {im:.3f} | {ib:.3f} |"
            )
        except Exception as exc:  # noqa: BLE001
            lines.append(f"| `{p.name}` | ERROR | | | | | `{exc}` |")

    lines.append("\n## Notes\n")
    lines.append("- **ink** is the proportion of non-white glyph pixels in sample strings (higher = bolder/denser).\n")
    lines.append("- **digit span** (min to max width): tight range is better for tabular stability.\n")
    lines.append("- Rebuild from OTF with `tools/apple2026_rebuild_fonts_from_otf.py` when sources exist.\n")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=REPORT)
    ap.add_argument("--fonts-dir", type=Path, default=FONTS_DIR)
    args = ap.parse_args()

    text = analyze_all(args.fonts_dir)
    args.out.write_text(text, encoding="utf-8")
    print(text)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
